sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rogerwesterbo/docker-react .

script:
  - docker run -e CI=true rogerwesterbo/docker-react npm run test -- --coverage